---
collections:
  # OpenShift and Kubernetes management
  - name: kubernetes.core
    version: ">=2.4.0"
  
  - name: redhat.openshift
    version: ">=2.0.0"
  
  - name: community.okd
    version: ">=2.0.0"
  
  # Ansible Automation Platform collections
  - name: ansible.controller
    version: ">=4.0.0"
  
  # Event Driven Ansible
  - name: ansible.eda
    version: ">=1.0.0"
  
  # Infrastructure and system management
  - name: community.general
    version: ">=5.0.0"
  
  - name: ansible.posix
    version: ">=1.0.0"
  
  - name: community.crypto
    version: ">=2.0.0"
  
  # Container and registry management
  - name: containers.podman
    version: ">=1.0.0"
  
  # Monitoring and observability
  - name: community.grafana
    version: ">=1.0.0"
  
  # Helm for operator management
  - name: community.kubernetes
    version: ">=2.0.0"

roles:
  # OpenShift specific roles
  - name: redhat.openshift_virtualization
    version: ">=1.0.0" 