---
all:
  children:
    openshift_clusters:
      hosts:
        openshift-cluster-prod:
          ansible_host: api.openshift.example.com
          ansible_port: 6443
          ansible_user: system:admin
          k8s_auth_kubeconfig: ~/.kube/config-prod
      vars:
        openshift_cluster_name: "production"
        openshift_domain: "apps.openshift.example.com"
        openshift_api_url: "https://api.openshift.example.com:6443"
        openshift_console_url: "https://console-openshift-console.apps.openshift.example.com"
    
    bastion_hosts:
      hosts:
        bastion-prod:
          ansible_host: 10.0.1.10
          ansible_user: ansible
      vars:
        # Used for accessing OpenShift cluster and running oc/kubectl commands
        oc_binary_path: "/usr/local/bin/oc"
        kubectl_binary_path: "/usr/local/bin/kubectl"

  vars:
    # Global variables
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # AAP Operator Configuration
    aap_version: "2.5"
    aap_operator_version: "2.5.0"
    aap_namespace: "ansible-automation-platform"
    
    # OpenShift Configuration
    openshift_version: "4.14"
    openshift_cluster_monitoring: true
    
    # AAP Components Configuration
    controller_replicas: 2
    hub_replicas: 1
    eda_replicas: 2
    
    # Storage Configuration
    storage_class: "gp3-csi"
    controller_storage_size: "20Gi"
    hub_storage_size: "100Gi"
    eda_storage_size: "20Gi"
    postgres_storage_size: "50Gi"
    
    # Resource Requirements
    controller_cpu_request: "1000m"
    controller_memory_request: "2Gi"
    controller_cpu_limit: "2000m"
    controller_memory_limit: "4Gi"
    
    hub_cpu_request: "1000m"
    hub_memory_request: "2Gi"
    hub_cpu_limit: "2000m"
    hub_memory_limit: "4Gi"
    
    eda_cpu_request: "500m"
    eda_memory_request: "1Gi"
    eda_cpu_limit: "1000m"
    eda_memory_limit: "2Gi"
    
    # Network Configuration
    controller_hostname: "controller.{{ openshift_domain }}"
    hub_hostname: "hub.{{ openshift_domain }}"
    eda_hostname: "eda.{{ openshift_domain }}"
    
    # SSL/TLS Configuration
    ssl_certificate_issuer: "letsencrypt-prod"
    ssl_certificate_duration: "8760h"  # 1 year
    
    # Backup configuration
    backup_enabled: true
    backup_retention_days: 30
    backup_schedule: "0 2 * * *"
    backup_storage_class: "gp3-csi" 