---
all:
  children:
    openshift_clusters:
      hosts:
        openshift-cluster-dev:
          ansible_host: api.openshift-dev.local
          ansible_port: 6443
          ansible_user: system:admin
          k8s_auth_kubeconfig: ~/.kube/config-dev
      vars:
        openshift_cluster_name: "development"
        openshift_domain: "apps.openshift-dev.local"
        openshift_api_url: "https://api.openshift-dev.local:6443"
        openshift_console_url: "https://console-openshift-console.apps.openshift-dev.local"
    
    bastion_hosts:
      hosts:
        bastion-dev:
          ansible_host: 192.168.1.10
          ansible_user: ansible
      vars:
        oc_binary_path: "/usr/local/bin/oc"
        kubectl_binary_path: "/usr/local/bin/kubectl"

  vars:
    # Global variables
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    
    # AAP Operator Configuration
    aap_version: "2.5"
    aap_operator_version: "2.5.0"
    aap_namespace: "ansible-automation-platform-dev"
    
    # OpenShift Configuration
    openshift_version: "4.14"
    openshift_cluster_monitoring: true
    
    # AAP Components Configuration (smaller for dev)
    controller_replicas: 1
    hub_replicas: 1
    eda_replicas: 1
    
    # Storage Configuration
    storage_class: "standard"
    controller_storage_size: "10Gi"
    hub_storage_size: "50Gi"
    eda_storage_size: "10Gi"
    postgres_storage_size: "20Gi"
    
    # Resource Requirements (smaller for dev)
    controller_cpu_request: "500m"
    controller_memory_request: "1Gi"
    controller_cpu_limit: "1000m"
    controller_memory_limit: "2Gi"
    
    hub_cpu_request: "500m"
    hub_memory_request: "1Gi"
    hub_cpu_limit: "1000m"
    hub_memory_limit: "2Gi"
    
    eda_cpu_request: "250m"
    eda_memory_request: "512Mi"
    eda_cpu_limit: "500m"
    eda_memory_limit: "1Gi"
    
    # Network Configuration
    controller_hostname: "controller.{{ openshift_domain }}"
    hub_hostname: "hub.{{ openshift_domain }}"
    eda_hostname: "eda.{{ openshift_domain }}"
    
    # SSL/TLS Configuration
    ssl_certificate_issuer: "selfsigned"
    ssl_certificate_duration: "8760h"
    
    # Development specific settings
    debug_mode: true
    ssl_verify: false
    backup_enabled: false 